// Package state manages the .aegis/ directory where aegisctl persists
// analysis results (state.json) and recommendation plans (plan.json)
// between the init, plan, and apply commands.
package state

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"time"
)

const (
	// DirName is the directory used to store aegis state.
	DirName = ".aegis"

	stateFile = "state.json"
	planFile  = "plan.json"
)

// AnalysisState holds the persisted output of "aegisctl init".
type AnalysisState struct {
	Version   string    `json:"version"`
	CreatedAt time.Time `json:"created_at"`
	RepoPath  string    `json:"repo_path"`

	// Heuristic findings from the local analyzer.
	Heuristic HeuristicFindings `json:"heuristic"`

	// LLM-enriched analysis (nil if running in offline/heuristic mode).
	Enriched *EnrichedAnalysis `json:"enriched,omitempty"`

	// Mode records whether LLM was used.
	Mode string `json:"mode"` // "copilot" or "heuristic"
}

// HeuristicFindings mirrors the key data from analyzer.Findings in a
// JSON-friendly structure.
type HeuristicFindings struct {
	Languages   []Language      `json:"languages"`
	HasDocker   bool            `json:"has_docker"`
	Dockerfiles []string        `json:"dockerfiles"`
	CI          CIInfo          `json:"ci"`
	IaC         IaCInfo         `json:"iac"`
	Deps        []Dependency    `json:"deps"`
	AWSHints    []AWSHint       `json:"aws_hints"`
	Secrets     []SecretFinding `json:"secrets"`
	FileCount   int             `json:"file_count"`
}

// Language records a detected language.
type Language struct {
	Language string `json:"language"`
	Evidence string `json:"evidence"`
}

// CIInfo describes detected CI/CD.
type CIInfo struct {
	HasGitHubActions bool     `json:"has_github_actions"`
	Workflows        []string `json:"workflows"`
	HasOtherCI       bool     `json:"has_other_ci"`
	OtherCI          string   `json:"other_ci,omitempty"`
}

// IaCInfo describes detected IaC.
type IaCInfo struct {
	HasBicep            bool     `json:"has_bicep"`
	BicepFiles          []string `json:"bicep_files,omitempty"`
	HasTerraform        bool     `json:"has_terraform"`
	TerraformFiles      []string `json:"terraform_files,omitempty"`
	HasARM              bool     `json:"has_arm"`
	ARMFiles            []string `json:"arm_files,omitempty"`
	HasCDK              bool     `json:"has_cdk"`
	HasCloudFormation   bool     `json:"has_cloudformation"`
	CloudFormationFiles []string `json:"cloudformation_files,omitempty"`
}

// Dependency records a dependency signal.
type Dependency struct {
	File    string `json:"file"`
	Type    string `json:"type"`
	Details string `json:"details"`
}

// AWSHint records an AWS service signal.
type AWSHint struct {
	Service  string `json:"service"`
	File     string `json:"file"`
	Line     int    `json:"line"`
	Evidence string `json:"evidence"`
}

// SecretFinding records a detected secret.
type SecretFinding struct {
	File        string `json:"file"`
	Line        int    `json:"line"`
	Type        string `json:"type"`
	Severity    string `json:"severity"`
	Evidence    string `json:"evidence"`
	Remediation string `json:"remediation"`
}

// EnrichedAnalysis is the LLM-produced enrichment of the heuristic findings.
type EnrichedAnalysis struct {
	AppType            string   `json:"app_type"`
	AppDescription     string   `json:"app_description"`
	PrimaryLanguage    string   `json:"primary_language"`
	RecommendedRuntime string   `json:"recommended_runtime"`
	NeedsDatabase      bool     `json:"needs_database"`
	DatabaseHints      []string `json:"database_hints"`
	NeedsCache         bool     `json:"needs_cache"`
	NeedsQueue         bool     `json:"needs_queue"`
	NeedsStorage       bool     `json:"needs_storage"`
	IsContainerized    bool     `json:"is_containerized"`
	ContainerReady     bool     `json:"container_ready"`
	HasExistingIaC     bool     `json:"has_existing_iac"`
	ExistingIaCQuality string   `json:"existing_iac_quality"`
	IaCIssues          []string `json:"iac_issues"`
	HasExistingCICD    bool     `json:"has_existing_cicd"`
	CICDQuality        string   `json:"cicd_quality"`
	CICDIssues         []string `json:"cicd_issues"`
	SecurityConcerns   []string `json:"security_concerns"`
	AWSMigrationNeeded bool     `json:"aws_migration_needed"`
	AWSServicesFound   []string `json:"aws_services_detected"`
	Complexity         string   `json:"complexity"`
}

// Plan holds the persisted output of "aegisctl plan".
type Plan struct {
	Version   string    `json:"version"`
	CreatedAt time.Time `json:"created_at"`
	RepoPath  string    `json:"repo_path"`

	// SelectedOption is the index (0-based) of the chosen option.
	SelectedOption int `json:"selected_option"`

	// Options are the architecture alternatives generated by the LLM/heuristic.
	Options []ArchOption `json:"options"`

	// SecretsRemediation are specific remediation steps for detected secrets.
	SecretsRemediation []SecretsRemediationItem `json:"secrets_remediation,omitempty"`

	// CICDRecommendation is the recommended CI/CD pipeline configuration.
	CICDRecommendation *CICDRecommendation `json:"cicd_recommendation,omitempty"`

	// Mode records whether LLM was used.
	Mode string `json:"mode"` // "copilot" or "heuristic"
}

// ArchOption represents one architecture alternative.
type ArchOption struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Recommended bool   `json:"recommended"`

	Compute    ComputeChoice    `json:"compute"`
	Data       []DataService    `json:"data"`
	Security   SecurityChoice   `json:"security"`
	Monitoring MonitoringChoice `json:"monitoring"`
	Networking NetworkingChoice `json:"networking"`

	EstimatedCostDev  string    `json:"estimated_monthly_cost_dev"`
	EstimatedCostProd string    `json:"estimated_monthly_cost_prod"`
	WAFScores         WAFScores `json:"waf_scores"`

	MigrationSteps  []string `json:"migration_steps,omitempty"`
	FilesToGenerate []string `json:"files_to_generate"`
}

// ComputeChoice describes the compute recommendation.
type ComputeChoice struct {
	Service   string `json:"service"`
	SKU       string `json:"sku"`
	SKUProd   string `json:"sku_prod"`
	Rationale string `json:"rationale"`
}

// DataService describes an Azure data/storage service.
type DataService struct {
	Service string `json:"service"`
	Purpose string `json:"purpose"`
	SKU     string `json:"sku"`
}

// SecurityChoice describes the security architecture.
type SecurityChoice struct {
	Identity     string   `json:"identity"`
	SecretsStore string   `json:"secrets_store"`
	ConfigStore  string   `json:"config_store"`
	Additional   []string `json:"additional"`
}

// MonitoringChoice describes the monitoring setup.
type MonitoringChoice struct {
	Service    string   `json:"service"`
	Additional []string `json:"additional"`
}

// NetworkingChoice describes networking configuration.
type NetworkingChoice struct {
	HTTPSOnly  bool     `json:"https_only"`
	MinTLS     string   `json:"min_tls"`
	Additional []string `json:"additional"`
}

// WAFScores per architecture option.
type WAFScores struct {
	Reliability            int `json:"reliability"`
	Security               int `json:"security"`
	CostOptimization       int `json:"cost_optimization"`
	OperationalExcellence  int `json:"operational_excellence"`
	PerformanceEfficiency  int `json:"performance_efficiency"`
}

// SecretsRemediationItem is a specific secret migration step.
type SecretsRemediationItem struct {
	Current     string   `json:"current"`
	Recommended string   `json:"recommended"`
	Steps       []string `json:"steps"`
}

// CICDRecommendation is the recommended pipeline setup.
type CICDRecommendation struct {
	Workflows               []WorkflowRecommendation `json:"workflows"`
	ImprovementsOverExisting []string                 `json:"improvements_over_existing,omitempty"`
}

// WorkflowRecommendation describes a single workflow file.
type WorkflowRecommendation struct {
	Name     string   `json:"name"`
	File     string   `json:"file"`
	Purpose  string   `json:"purpose"`
	Triggers []string `json:"triggers"`
}

// --- File I/O ---

// Dir returns the .aegis directory path for the given repo.
func Dir(repoPath string) string {
	return filepath.Join(repoPath, DirName)
}

// EnsureDir creates the .aegis directory if it doesn't exist.
func EnsureDir(repoPath string) error {
	dir := Dir(repoPath)
	return os.MkdirAll(dir, 0755)
}

// SaveState writes the analysis state to .aegis/state.json.
func SaveState(repoPath string, s *AnalysisState) error {
	if err := EnsureDir(repoPath); err != nil {
		return fmt.Errorf("creating .aegis dir: %w", err)
	}
	data, err := json.MarshalIndent(s, "", "  ")
	if err != nil {
		return fmt.Errorf("marshaling state: %w", err)
	}
	path := filepath.Join(Dir(repoPath), stateFile)
	return os.WriteFile(path, data, 0644)
}

// LoadState reads the analysis state from .aegis/state.json.
func LoadState(repoPath string) (*AnalysisState, error) {
	path := filepath.Join(Dir(repoPath), stateFile)
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading state (run 'aegisctl init' first): %w", err)
	}
	var s AnalysisState
	if err := json.Unmarshal(data, &s); err != nil {
		return nil, fmt.Errorf("parsing state: %w", err)
	}
	return &s, nil
}

// SavePlan writes the recommendation plan to .aegis/plan.json.
func SavePlan(repoPath string, p *Plan) error {
	if err := EnsureDir(repoPath); err != nil {
		return fmt.Errorf("creating .aegis dir: %w", err)
	}
	data, err := json.MarshalIndent(p, "", "  ")
	if err != nil {
		return fmt.Errorf("marshaling plan: %w", err)
	}
	path := filepath.Join(Dir(repoPath), planFile)
	return os.WriteFile(path, data, 0644)
}

// LoadPlan reads the plan from .aegis/plan.json.
func LoadPlan(repoPath string) (*Plan, error) {
	path := filepath.Join(Dir(repoPath), planFile)
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading plan (run 'aegisctl plan' first): %w", err)
	}
	var p Plan
	if err := json.Unmarshal(data, &p); err != nil {
		return nil, fmt.Errorf("parsing plan: %w", err)
	}
	return &p, nil
}

// StateExists checks if .aegis/state.json exists.
func StateExists(repoPath string) bool {
	path := filepath.Join(Dir(repoPath), stateFile)
	_, err := os.Stat(path)
	return err == nil
}

// PlanExists checks if .aegis/plan.json exists.
func PlanExists(repoPath string) bool {
	path := filepath.Join(Dir(repoPath), planFile)
	_, err := os.Stat(path)
	return err == nil
}
