// ============================================================================
// Aegis — Main Bicep Template (Scaffold)
// ============================================================================
// This is a minimal scaffold generated by Aegis. It demonstrates the intended
// structure for a minimum-cost Azure architecture. Expand with modules as
// needed.
//
// Deploy mode: Incremental ONLY (never Complete).
// Default SKUs: minimum-cost (Free/Basic for dev, Standard for prod).
// ============================================================================

// ---------------------------------------------------------------------------
// Parameters
// ---------------------------------------------------------------------------

@description('The name of the workload (used in resource naming).')
param workloadName string

@description('The deployment environment.')
@allowed([
  'dev'
  'staging'
  'prod'
])
param environment string = 'dev'

@description('The Azure region for all resources.')
param location string = resourceGroup().location

@description('Tags applied to all resources.')
param tags object = {
  project: 'aegis'
  environment: environment
  managedBy: 'bicep'
}

// ---------------------------------------------------------------------------
// Variables
// ---------------------------------------------------------------------------

var suffix = '${workloadName}-${environment}-${location}'

// SKU selection based on environment
var appServicePlanSku = environment == 'prod' ? 'S1' : 'F1'
var appConfigSku = environment == 'prod' ? 'Standard' : 'Free'

// ---------------------------------------------------------------------------
// Resources
// ---------------------------------------------------------------------------

// App Service Plan
resource appServicePlan 'Microsoft.Web/serverfarms@2023-12-01' = {
  name: 'plan-${suffix}'
  location: location
  tags: tags
  sku: {
    name: appServicePlanSku
  }
  kind: 'linux'
  properties: {
    reserved: true // Required for Linux
  }
}

// App Service
resource appService 'Microsoft.Web/sites@2023-12-01' = {
  name: 'app-${suffix}'
  location: location
  tags: tags
  identity: {
    type: 'SystemAssigned' // Managed Identity — no stored credentials
  }
  properties: {
    serverFarmId: appServicePlan.id
    httpsOnly: true
    siteConfig: {
      minTlsVersion: '1.2'
      ftpsState: 'Disabled'
      // TODO: Configure app settings referencing Key Vault / App Configuration
    }
  }
}

// Key Vault (for secrets that cannot use Managed Identity)
resource keyVault 'Microsoft.KeyVault/vaults@2023-07-01' = {
  name: 'kv-${workloadName}-${environment}'
  location: location
  tags: tags
  properties: {
    sku: {
      family: 'A'
      name: 'standard'
    }
    tenantId: subscription().tenantId
    enableRbacAuthorization: true // Use RBAC, not access policies
    enableSoftDelete: true
    softDeleteRetentionInDays: 90
    // TODO: Add RBAC role assignments for the App Service managed identity
  }
}

// App Configuration (for non-secret configuration)
resource appConfig 'Microsoft.AppConfiguration/configurationStores@2023-03-01' = {
  name: 'appcs-${workloadName}-${environment}'
  location: location
  tags: tags
  sku: {
    name: appConfigSku
  }
  // TODO: Add key-value pairs for non-secret configuration
}

// TODO: Add Application Insights + Log Analytics workspace
// TODO: Add RBAC role assignments (Key Vault Secrets User, App Config Data Reader)
// TODO: Add additional modules as needed (database, storage, CDN, etc.)

// ---------------------------------------------------------------------------
// Outputs
// ---------------------------------------------------------------------------

output appServiceName string = appService.name
output appServiceDefaultHostname string = appService.properties.defaultHostName
output keyVaultName string = keyVault.name
output keyVaultUri string = keyVault.properties.vaultUri
output appConfigName string = appConfig.name
output appConfigEndpoint string = appConfig.properties.endpoint
