package output

// This file contains all embedded templates used by the pack, score, and
// migrate-aws generators. Templates use Go text/template syntax.

// ----------------------------------------------------------------
// Documentation templates
// ----------------------------------------------------------------

const ArchitectureDocTmpl = `# Architecture — WAF-Aligned Decisions

> Generated by aegisctl pack. Based on analysis of: {{.RepoPath}}

---

## Terminology note

**WAF** = Azure Well-Architected Framework (not Web Application Firewall).

**CAF** = Azure Cloud Adoption Framework — assumed as the landing-zone
foundation. Aegis focuses on WAF pillar analysis.

---

## Detected Application Profile

| Field | Value |
|---|---|
| Repository | {{.RepoPath}} |
| Languages | {{if .Languages}}{{range $i, $l := .Languages}}{{if $i}}, {{end}}{{$l.Language}}{{end}}{{else}}Not detected{{end}} |
| Container support | {{if .HasDocker}}Yes{{else}}No{{end}} |
| CI/CD | {{if .CI.HasGitHubActions}}GitHub Actions{{else if .CI.HasOtherCI}}{{.CI.OtherCI}}{{else}}Not detected{{end}} |
| IaC | {{if .IaC.HasBicep}}Bicep{{else if .IaC.HasTerraform}}Terraform (migrate to Bicep recommended){{else if .IaC.HasARM}}ARM (migrate to Bicep recommended){{else}}Not detected{{end}} |
| AWS signals | {{if .AWSHints}}{{len .AWSHints}} finding(s){{else}}None{{end}} |
| Secret findings | {{if .Secrets}}{{len .Secrets}} finding(s) — see Security doc{{else}}None{{end}} |

---

## Recommended Azure Architecture (Minimum Cost)

### Compute
{{if .HasDocker}}- **Azure Container Apps** — scale-to-zero, consumption pricing.
{{else}}- **Azure App Service** (Linux, Free/Basic tier for dev).
{{end}}
### Identity & Security
- **Managed Identity** (system-assigned) for all Azure service access.
- **Azure Key Vault** for secrets that cannot use Managed Identity.
- **Azure App Configuration** for non-secret settings.

### Monitoring
- **Application Insights** + **Log Analytics** workspace.
- Health probes configured in compute resource.

### Networking
- HTTPS-only, TLS 1.2 minimum.
- FTPS disabled.

---

## Pillar-by-pillar Assessment

### 1. Reliability
- PaaS compute with built-in health checks and auto-restart.
- Single-region default (multi-region documented but not default).

### 2. Security
- Managed Identity first; Key Vault for residual secrets.
- Secret scan: {{if .Secrets}}{{len .Secrets}} finding(s) require remediation.{{else}}No issues detected.{{end}}

### 3. Cost Optimization
- Minimum-viable SKUs: Free/Basic for dev, Standard for prod.
- Consumption-based compute where possible.

### 4. Operational Excellence
- GitHub Actions CI/CD (three-workflow pattern).
- IaC-only changes (Bicep, Incremental mode).
- Environment approvals for all deployments.

### 5. Performance Efficiency
- Autoscale rules scaffolded with conservative defaults.
- CDN/caching recommendations documented when applicable.

---

## References

- [Azure Well-Architected Framework](https://learn.microsoft.com/azure/well-architected/)
- [Cloud Adoption Framework](https://learn.microsoft.com/azure/cloud-adoption-framework/)
`

const SecurityDocTmpl = `# Security & Secrets — Findings and Remediation

> Generated by aegisctl pack. Repository: {{.RepoPath}}

---

## Remediation Hierarchy

1. **Managed Identity** — eliminate credentials entirely (preferred).
2. **Azure Key Vault** — for secrets that cannot use Managed Identity.
3. **Azure App Configuration** — for non-secret configuration values.

---

## Findings

{{if .Secrets}}**{{len .Secrets}} finding(s) detected.**

| # | File | Line | Type | Severity | Evidence | Remediation |
|---|---|---|---|---|---|---|
{{range $i, $s := .Secrets}}| {{inc $i}} | {{$s.File}} | {{$s.Line}} | {{$s.Type}} | {{$s.Severity}} | {{$s.Evidence}} | {{$s.Remediation}} |
{{end}}
{{else}}No secrets or credentials detected in repository scan.

This does not guarantee the absence of secrets — manual review is recommended.
{{end}}

---

## Remediation Patterns

### Pattern A: Replace hardcoded connection string with Managed Identity
1. Enable system-assigned Managed Identity on compute resource.
2. Grant RBAC role (e.g., Storage Blob Data Contributor) to the identity.
3. Remove connection string from code/config.
4. Use DefaultAzureCredential in application code.

### Pattern B: Move API key to Key Vault
1. Store the key as a Key Vault secret.
2. Grant the compute resource's Managed Identity "Key Vault Secrets User" role.
3. Reference the secret via Key Vault URI in App Configuration or environment variable.
4. Remove the key from source code.

### Pattern C: Move non-secret config to App Configuration
1. Identify values that are not secrets (feature flags, endpoints, etc.).
2. Store them in Azure App Configuration.
3. Reference via Managed Identity from application code.

---

## CI/CD Integration

- Add pre-commit hook or gitleaks scan to CI pipeline.
- Use GitHub secret scanning (enabled by default on public repos).
- Store deployment credentials using OIDC federation (no long-lived secrets).
`

const WAFChecklistTmpl = `# WAF Checklist

> Generated by aegisctl. Repository: {{.RepoPath}}
>
> Based on the Azure Well-Architected Framework (WAF).
> **WAF** = Well-Architected Framework (not Web Application Firewall).

---

## Reliability

| # | Check | Status | Notes |
|---|---|---|---|
| RE-01 | Health endpoints configured | {{if .HasDocker}}Needs confirmation{{else}}TODO{{end}} | |
| RE-02 | Auto-restart / self-healing enabled | {{relyOnCompute .}} | PaaS provides this by default |
| RE-03 | Retry policies for external calls | TODO | |
| RE-04 | Circuit breaker pattern considered | TODO | |
| RE-05 | Data backup strategy defined | TODO | |
| RE-06 | Disaster recovery plan documented | TODO | |
| RE-07 | Multi-region failover (if required) | Not default | Minimum-cost = single region |
| RE-08 | Dependency health monitoring | TODO | |
| RE-09 | Graceful degradation strategy | TODO | |
| RE-10 | Chaos testing considered | TODO | |

## Security

| # | Check | Status | Notes |
|---|---|---|---|
| SE-01 | Managed Identity enabled | Recommended | Scaffolded in IaC |
| SE-02 | No hardcoded secrets | {{if .Secrets}}{{len .Secrets}} finding(s){{else}}Pass{{end}} | |
| SE-03 | Key Vault for residual secrets | Recommended | Scaffolded in IaC |
| SE-04 | HTTPS-only enforced | Recommended | Scaffolded in IaC |
| SE-05 | TLS 1.2+ minimum | Recommended | Scaffolded in IaC |
| SE-06 | RBAC least-privilege | TODO | |
| SE-07 | Network segmentation | TODO | |
| SE-08 | Dependency vulnerability scanning | TODO | |
| SE-09 | Secret rotation plan | TODO | |
| SE-10 | Security baseline documented | TODO | |

## Cost Optimization

| # | Check | Status | Notes |
|---|---|---|---|
| CO-01 | Minimum-viable SKU selected | Recommended | Free/Basic for dev |
| CO-02 | Consumption-based pricing where possible | Recommended | |
| CO-03 | Auto-shutdown for dev/test | TODO | |
| CO-04 | Right-sizing reviewed | TODO | |
| CO-05 | Reserved instances considered (prod) | TODO | |
| CO-06 | Cost alerts configured | TODO | |
| CO-07 | Unused resources identified | TODO | |
| CO-08 | Storage tier optimization | TODO | |
| CO-09 | Egress costs estimated | TODO | |
| CO-10 | Cost centre tagging | TODO | |

## Operational Excellence

| # | Check | Status | Notes |
|---|---|---|---|
| OE-01 | IaC for all resources | {{if .IaC.HasBicep}}Bicep detected{{else}}Recommended{{end}} | |
| OE-02 | CI pipeline (build + test) | {{if .CI.HasGitHubActions}}Detected{{else}}TODO{{end}} | |
| OE-03 | CD pipeline (gated deploy) | {{deployStatus .}} | |
| OE-04 | Environment approvals | Recommended | GitHub Environments |
| OE-05 | Monitoring and alerting | TODO | App Insights recommended |
| OE-06 | Runbook / incident response | TODO | |
| OE-07 | Change management process | TODO | |
| OE-08 | Documentation up to date | Generated | This pack |
| OE-09 | Post-deployment validation | TODO | |
| OE-10 | Rollback plan documented | TODO | |

## Performance Efficiency

| # | Check | Status | Notes |
|---|---|---|---|
| PE-01 | Autoscale configured | TODO | Scaffolded in IaC |
| PE-02 | CDN for static assets | TODO | |
| PE-03 | Caching strategy | TODO | |
| PE-04 | Database query optimization | TODO | |
| PE-05 | Connection pooling | TODO | |
| PE-06 | Async processing for heavy tasks | TODO | |
| PE-07 | Load testing plan | TODO | |
| PE-08 | Response time targets defined | TODO | |
| PE-09 | Resource limits configured | TODO | |
| PE-10 | Compression enabled | TODO | |
`

const WAFScorecardTmpl = `# WAF Scorecard

> Generated by aegisctl score. Repository: {{.RepoPath}}

---

> **⚠️ Disclaimer:** This scorecard uses heuristic analysis and is
> **not an official Microsoft assessment**. Scores are not endorsed by
> Microsoft. Use as a starting point for architectural review.

---

## Scoring Summary

| Pillar | Score (0–5) | Rationale |
|---|---|---|
| Reliability | {{.Scores.Reliability}} / 5 | {{.Rationale.Reliability}} |
| Security | {{.Scores.Security}} / 5 | {{.Rationale.Security}} |
| Cost Optimization | {{.Scores.CostOpt}} / 5 | {{.Rationale.CostOpt}} |
| Operational Excellence | {{.Scores.OpsExcel}} / 5 | {{.Rationale.OpsExcel}} |
| Performance Efficiency | {{.Scores.PerfEff}} / 5 | {{.Rationale.PerfEff}} |
| **Overall** | **{{.Scores.Overall}} / 5** | Weighted average |

---

## Top 5 Improvements

{{range $i, $imp := .Improvements}}{{inc $i}}. **{{$imp.Title}}** ({{$imp.Pillar}}, impact: {{$imp.Impact}})
   {{$imp.Description}}
{{end}}

---

## Pillar Details

### Reliability ({{.Scores.Reliability}}/5)
**Strengths:** {{.Details.ReliabilityStrengths}}
**Gaps:** {{.Details.ReliabilityGaps}}

### Security ({{.Scores.Security}}/5)
**Strengths:** {{.Details.SecurityStrengths}}
**Gaps:** {{.Details.SecurityGaps}}

### Cost Optimization ({{.Scores.CostOpt}}/5)
**Strengths:** {{.Details.CostOptStrengths}}
**Gaps:** {{.Details.CostOptGaps}}

### Operational Excellence ({{.Scores.OpsExcel}}/5)
**Strengths:** {{.Details.OpsExcelStrengths}}
**Gaps:** {{.Details.OpsExcelGaps}}

### Performance Efficiency ({{.Scores.PerfEff}}/5)
**Strengths:** {{.Details.PerfEffStrengths}}
**Gaps:** {{.Details.PerfEffGaps}}
`

const AWSMigrationTmpl = `# AWS → Azure Migration Assessment

> Generated by aegisctl migrate-aws. Repository: {{.RepoPath}}

---

> **⚠️ Disclaimer:** This mapping is **best-effort and advisory**. Service
> parity between AWS and Azure is not always 1:1. Each mapping must be
> validated by the engineering team before adoption.

---

## Detected AWS Services

{{if .AWSHints}}
| # | AWS Service | File | Line | Evidence |
|---|---|---|---|---|
{{range $i, $h := .AWSHints}}| {{inc $i}} | {{$h.Service}} | {{$h.File}} | {{$h.Line}} | {{$h.Evidence}} |
{{end}}
{{else}}No AWS service usage detected in the repository.
{{end}}

---

## Service Mapping

{{if .Mappings}}
| # | AWS Service Detected | Azure Equivalent | Confidence | Migration Notes |
|---|---|---|---|---|
{{range $i, $m := .Mappings}}| {{inc $i}} | {{$m.AWSService}} | {{$m.AzureEquivalent}} | {{$m.Confidence}} | {{$m.Notes}} |
{{end}}
{{else}}No AWS services detected — no mapping required.
{{end}}

---

## Migration Checklist

- [ ] Validate each mapping with engineering team
- [ ] Estimate code change effort per service
- [ ] Update IaC from CloudFormation/Terraform to Bicep
- [ ] Update CI/CD to GitHub Actions targeting Azure
- [ ] Re-implement secrets (Managed Identity → Key Vault)
- [ ] Update monitoring to Azure Monitor + App Insights
- [ ] Plan data migration strategy
- [ ] Execute non-production migration first
- [ ] Production migration with rollback plan

---

## References

- [Azure for AWS professionals](https://learn.microsoft.com/azure/architecture/aws-professional/)
- [AWS to Azure services comparison](https://learn.microsoft.com/azure/architecture/aws-professional/services)
`

// ----------------------------------------------------------------
// IaC templates
// ----------------------------------------------------------------

const BicepMainTmpl = `// Aegis — Generated Bicep Template
// Repository: {{.RepoPath}}
// Deploy mode: {{.DeployMode}}
//
// ⚠️ This is a scaffold. Review and customize before deploying.
// ⚠️ Default: generate-only. No deployment without explicit opt-in.

targetScope = 'resourceGroup'

// ----------------------------------------------------------------
// Parameters
// ----------------------------------------------------------------

@description('Base name for all resources')
param workloadName string = 'aegis'

@allowed(['dev', 'staging', 'prod'])
@description('Environment (affects SKU selection)')
param environment string = 'dev'

@description('Azure region')
param location string = resourceGroup().location

@description('Resource tags')
param tags object = {
  project: workloadName
  environment: environment
  managedBy: 'bicep'
  generatedBy: 'aegisctl'
}

// ----------------------------------------------------------------
// Variables
// ----------------------------------------------------------------

var suffix = '${workloadName}-${environment}'
var appServicePlanSku = environment == 'prod' ? 'S1' : 'F1'
var keyVaultSku = 'standard'
var appConfigSku = environment == 'prod' ? 'Standard' : 'Free'

// ----------------------------------------------------------------
// Resources
// ----------------------------------------------------------------

// App Service Plan
resource appServicePlan 'Microsoft.Web/serverfarms@2023-01-01' = {
  name: 'plan-${suffix}'
  location: location
  tags: tags
  kind: 'linux'
  sku: {
    name: appServicePlanSku
  }
  properties: {
    reserved: true // Linux
  }
}

// App Service
resource appService 'Microsoft.Web/sites@2023-01-01' = {
  name: 'app-${suffix}'
  location: location
  tags: tags
  identity: {
    type: 'SystemAssigned' // Managed Identity — no credentials needed
  }
  properties: {
    serverFarmId: appServicePlan.id
    httpsOnly: true
    siteConfig: {
      minTlsVersion: '1.2'
      ftpsState: 'Disabled'
      alwaysOn: environment == 'prod'
      linuxFxVersion: '{{.LinuxFxVersion}}'
    }
  }
}

// Key Vault
resource keyVault 'Microsoft.KeyVault/vaults@2023-07-01' = {
  name: 'kv-${suffix}'
  location: location
  tags: tags
  properties: {
    sku: {
      family: 'A'
      name: keyVaultSku
    }
    tenantId: subscription().tenantId
    enableRbacAuthorization: true
    enableSoftDelete: true
    softDeleteRetentionInDays: 90
  }
}

// App Configuration
resource appConfig 'Microsoft.AppConfiguration/configurationStores@2023-03-01' = {
  name: 'appcs-${suffix}'
  location: location
  tags: tags
  sku: {
    name: appConfigSku
  }
}

// TODO: Add Application Insights + Log Analytics workspace
// TODO: Add RBAC role assignments for Managed Identity → Key Vault
// TODO: Add additional modules as needed

// ----------------------------------------------------------------
// Outputs
// ----------------------------------------------------------------

output appServiceName string = appService.name
output defaultHostname string = appService.properties.defaultHostName
output keyVaultName string = keyVault.name
output keyVaultUri string = keyVault.properties.vaultUri
output appConfigName string = appConfig.name
`

// ----------------------------------------------------------------
// Workflow templates
// ----------------------------------------------------------------

const CIWorkflowTmpl = `# CI — Build & Test
# Generated by aegisctl pack

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Check formatting
        working-directory: src
        run: |
          unformatted=$(gofmt -l .)
          if [ -n "$unformatted" ]; then
            echo "Files not formatted:"
            echo "$unformatted"
            exit 1
          fi

      - name: Run tests
        working-directory: src
        run: go test -v ./...

      - name: Build
        working-directory: src
        run: go build -o ../bin/aegisctl ./cmd/aegisctl
`

const IaCValidateWorkflowTmpl = `# IaC Validation — Bicep Lint & Build
# Generated by aegisctl pack

name: IaC Validate

on:
  push:
    paths: ['infra/**']
  pull_request:
    paths: ['infra/**']

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Bicep lint
        run: |
          # TODO: Install Bicep CLI if not available
          # az bicep install
          echo "TODO: az bicep lint --file infra/main.bicep"

      - name: Bicep build (validate)
        run: |
          # TODO: Validate Bicep compiles without errors
          # az bicep build --file infra/main.bicep --stdout > /dev/null
          echo "TODO: az bicep build --file infra/main.bicep"
`

const DeployWorkflowTmpl = `# Deploy — Approval-Gated Deployment
# Generated by aegisctl pack
# Deploy mode: {{.DeployMode}}
#
# ⚠️ SAFETY: This workflow requires GitHub Environment approval.
# ⚠️ No resources are created/modified without explicit approval.
# ⚠️ Mode 'Incremental' only — never 'Complete' (risk of deletion).

name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod
{{if eq .DeployMode "auto"}}  # Auto-deploy on push to main (still requires Environment approval)
  push:
    branches: [main]
    paths: ['infra/**']
{{end}}
permissions:
  id-token: write   # OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{"{{"}} github.event.inputs.environment || 'dev' {{"}}"}}  # ← Requires approval
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{"{{"}} secrets.AZURE_CLIENT_ID {{"}}"}}
          tenant-id: ${{"{{"}} secrets.AZURE_TENANT_ID {{"}}"}}
          subscription-id: ${{"{{"}} secrets.AZURE_SUBSCRIPTION_ID {{"}}"}}

      - name: What-If Preview
        run: |
          az deployment group what-if \
            --resource-group rg-aegis-${{"{{"}} github.event.inputs.environment || 'dev' {{"}}"}} \
            --template-file infra/main.bicep \
            --parameters infra/parameters.${{"{{"}} github.event.inputs.environment || 'dev' {{"}}"}}.json \
            --mode Incremental

{{if eq .DeployMode "off"}}      # ⚠️ Deploy mode is OFF. Deployment step is disabled.
      # To enable, regenerate with: aegisctl pack --deploy manual|auto
      - name: Deploy (DISABLED)
        if: false
        run: echo "Deploy mode is off. No deployment will occur."
{{else}}      - name: Deploy (Incremental only)
        run: |
          az deployment group create \
            --resource-group rg-aegis-${{"{{"}} github.event.inputs.environment || 'dev' {{"}}"}} \
            --template-file infra/main.bicep \
            --parameters infra/parameters.${{"{{"}} github.event.inputs.environment || 'dev' {{"}}"}}.json \
            --mode Incremental
{{end}}`
